mappings = {
    "MSSubClass": {
        20: "1-STORY 1946 & NEWER ALL STYLES",
        30: "1-STORY 1945 & OLDER",
        40: "1-STORY W/FINISHED ATTIC ALL AGES",
        45: "1-1/2 STORY - UNFINISHED ALL AGES",
        50: "1-1/2 STORY FINISHED ALL AGES",
        60: "2-STORY 1946 & NEWER",
        70: "2-STORY 1945 & OLDER",
        75: "2-1/2 STORY ALL AGES",
        80: "SPLIT OR MULTI-LEVEL",
        85: "SPLIT FOYER",
        90: "DUPLEX - ALL STYLES AND AGES",
        120: "1-STORY PUD (Planned Unit Development) - 1946 & NEWER",
        150: "1-1/2 STORY PUD - ALL AGES",
        160: "2-STORY PUD - 1946 & NEWER",
        180: "PUD - MULTILEVEL - INCL SPLIT LEV/FOYER",
        190: "2 FAMILY CONVERSION - ALL STYLES AND AGES",
    },
    "MSZoning": {
        "A": "Agriculture",
        "C": "Commercial",
        "FV": "Floating Village Residential",
        "I": "Industrial",
        "RH": "Residential High Density",
        "RL": "Residential Low Density",
        "RP": "Residential Low Density Park",
        "RM": "Residential Medium Density",
    },
    "Street": {
        "Grvl": "Gravel",
        "Pave": "Paved",
    },
    "Alley": {
        "Grvl": "Gravel",
        "Pave": "Paved",
        "NA": "No Alley Access",
    },
    "LotShape": {
        "Reg": "Regular",
        "IR1": "Slightly Irregular",
        "IR2": "Moderately Irregular",
        "IR3": "Irregular",
    },
    "LandContour": {
        "Lvl": "Near Flat/Level",
        "Bnk": "Banked - Quick rise from street grade to building",
        "HLS": "Hillside - Significant side-to-side slope",
        "Low": "Depression",
    },
    "Utilities": {
        "AllPub": "All public Utilities (E,G,W,& S)",
        "NoSewr": "Electricity, Gas, and Water (Septic Tank)",
        "NoSeWa": "Electricity and Gas Only",
        "ELO": "Electricity Only",
    },
    "LotConfig": {
        "Inside": "Inside lot",
        "Corner": "Corner lot",
        "CulDSac": "Cul-de-sac",
        "FR2": "Frontage on 2 sides of property",
        "FR3": "Frontage on 3 sides of property",
    },
    "LandSlope": {
        "Gtl": "Gentle slope",
        "Mod": "Moderate slope",
        "Sev": "Severe slope",
    },
    "Neighborhood": {
        "Blmngtn": "Bloomington Heights",
        "Blueste": "Bluestem",
        "BrDale": "Briardale",
        "BrkSide": "Brookside",
        "ClearCr": "Clear Creek",
        "CollgCr": "College Creek",
        "Crawfor": "Crawford",
        "Edwards": "Edwards",
        "Gilbert": "Gilbert",
        "IDOTRR": "Iowa DOT and Rail Road",
        "MeadowV": "Meadow Village",
        "Mitchel": "Mitchell",
        "Names": "North Ames",
        "NoRidge": "Northridge",
        "NPkVill": "Northpark Villa",
        "NridgHt": "Northridge Heights",
        "NWAmes": "Northwest Ames",
        "OldTown": "Old Town",
        "SWISU": "South & West of Iowa State University",
        "Sawyer": "Sawyer",
        "SawyerW": "Sawyer West",
        "Somerst": "Somerset",
        "StoneBr": "Stone Brook",
        "Timber": "Timberland",
        "Veenker": "Veenker",
    },
    "Condition1": {
        "Artery": "Adjacent to arterial street",
        "Feedr": "Adjacent to feeder street",
        "Norm": "Normal",
        "RRNn": "Within 200' of North-South Railroad",
        "RRAn": "Adjacent to North-South Railroad",
        "PosN": "Near positive off-site feature (park, greenbelt, etc.)",
        "PosA": "Adjacent to positive off-site feature",
        "RRNe": "Within 200' of East-West Railroad",
        "RRAe": "Adjacent to East-West Railroad",
    },
    "Condition2": {  # same as Condition1
        "Artery": "Adjacent to arterial street",
        "Feedr": "Adjacent to feeder street",
        "Norm": "Normal",
        "RRNn": "Within 200' of North-South Railroad",
        "RRAn": "Adjacent to North-South Railroad",
        "PosN": "Near positive off-site feature (park, greenbelt, etc.)",
        "PosA": "Adjacent to positive off-site feature",
        "RRNe": "Within 200' of East-West Railroad",
        "RRAe": "Adjacent to East-West Railroad",
    },
    "BldgType": {
        "1Fam": "Single-family Detached",
        "2FmCon": "Two-family Conversion (originally one-family)",
        "Duplx": "Duplex",
        "TwnhsE": "Townhouse End Unit",
        "TwnhsI": "Townhouse Inside Unit",
    },
    "HouseStyle": {
        "1Story": "One story",
        "1.5Fin": "One and one-half story: 2nd level finished",
        "1.5Unf": "One and one-half story: 2nd level unfinished",
        "2Story": "Two story",
        "2.5Fin": "Two and one-half story: 2nd level finished",
        "2.5Unf": "Two and one-half story: 2nd level unfinished",
        "SFoyer": "Split Foyer",
        "SLvl": "Split Level",
    },
    "OverallQual": {
        10: "Very Excellent",
        9: "Excellent",
        8: "Very Good",
        7: "Good",
        6: "Above Average",
        5: "Average",
        4: "Below Average",
        3: "Fair",
        2: "Poor",
        1: "Very Poor",
    },
    "OverallCond": {
        10: "Very Excellent",
        9: "Excellent",
        8: "Very Good",
        7: "Good",
        6: "Above Average",
        5: "Average",
        4: "Below Average",
        3: "Fair",
        2: "Poor",
        1: "Very Poor",
    },
    "RoofStyle": {
        "Flat": "Flat",
        "Gable": "Gable",
        "Gambrel": "Gabrel (Barn)",
        "Hip": "Hip",
        "Mansard": "Mansard",
        "Shed": "Shed",
    },
    "RoofMatl": {
        "ClyTile": "Clay or Tile",
        "CompShg": "Standard (Composite) Shingle",
        "Membran": "Membrane",
        "Metal": "Metal",
        "Roll": "Roll",
        "Tar&Grv": "Gravel & Tar",
        "WdShake": "Wood Shakes",
        "WdShngl": "Wood Shingles",
    },
    "Exterior1st": {
        "AsbShng": "Asbestos Shingles",
        "AsphShn": "Asphalt Shingles",
        "BrkComm": "Brick Common",
        "BrkFace": "Brick Face",
        "CBlock": "Cinder Block",
        "CemntBd": "Cement Board",
        "HdBoard": "Hard Board",
        "ImStucc": "Imitation Stucco",
        "MetalSd": "Metal Siding",
        "Other": "Other",
        "Plywood": "Plywood",
        "PreCast": "PreCast",
        "Stone": "Stone",
        "Stucco": "Stucco",
        "VinylSd": "Vinyl Siding",
        "Wd Sdng": "Wood Siding",
        "WdShing": "Wood Shingles",
    },
    "Exterior2nd": {  # same as Exterior1st
        "AsbShng": "Asbestos Shingles",
        "AsphShn": "Asphalt Shingles",
        "BrkComm": "Brick Common",
        "BrkFace": "Brick Face",
        "CBlock": "Cinder Block",
        "CemntBd": "Cement Board",
        "HdBoard": "Hard Board",
        "ImStucc": "Imitation Stucco",
        "MetalSd": "Metal Siding",
        "Other": "Other",
        "Plywood": "Plywood",
        "PreCast": "PreCast",
        "Stone": "Stone",
        "Stucco": "Stucco",
        "VinylSd": "Vinyl Siding",
        "Wd Sdng": "Wood Siding",
        "WdShing": "Wood Shingles",
    },
    "MasVnrType": {
        "BrkCmn": "Brick Common",
        "BrkFace": "Brick Face",
        "CBlock": "Cinder Block",
        "None": "None",
        "Stone": "Stone",
    },
    "ExterQual": {"Ex": "Excellent", "Gd": "Good", "TA": "Average/Typical", "Fa": "Fair", "Po": "Poor"},
    "ExterCond": {"Ex": "Excellent", "Gd": "Good", "TA": "Average/Typical", "Fa": "Fair", "Po": "Poor"},
    "Foundation": {
        "BrkTil": "Brick & Tile",
        "CBlock": "Cinder Block",
        "PConc": "Poured Concrete",
        "Slab": "Slab",
        "Stone": "Stone",
        "Wood": "Wood",
    },
    "BsmtQual": {
        "Ex": "Excellent (100+ inches)",
        "Gd": "Good (90-99 inches)",
        "TA": "Typical (80-89 inches)",
        "Fa": "Fair (70-79 inches)",
        "Po": "Poor (<70 inches)",
        "NA": "No Basement",
    },
    "BsmtCond": {
        "Ex": "Excellent",
        "Gd": "Good",
        "TA": "Typical (slight dampness allowed)",
        "Fa": "Fair (dampness or some cracking/settling)",
        "Po": "Poor (severe cracking/settling/wetness)",
        "NA": "No Basement",
    },
    "BsmtExposure": {"Gd": "Good Exposure", "Av": "Average Exposure", "Mn": "Minimum Exposure", "No": "No Exposure", "NA": "No Basement"},
    "BsmtFinType1": {
        "GLQ": "Good Living Quarters",
        "ALQ": "Average Living Quarters",
        "BLQ": "Below Average Living Quarters",
        "Rec": "Average Rec Room",
        "LwQ": "Low Quality",
        "Unf": "Unfinished",
        "NA": "No Basement",
    },
    "BsmtFinType2": {  # same as BsmtFinType1
        "GLQ": "Good Living Quarters",
        "ALQ": "Average Living Quarters",
        "BLQ": "Below Average Living Quarters",
        "Rec": "Average Rec Room",
        "LwQ": "Low Quality",
        "Unf": "Unfinished",
        "NA": "No Basement",
    },
    "Heating": {
        "Floor": "Floor Furnace",
        "GasA": "Gas forced warm air furnace",
        "GasW": "Gas hot water or steam heat",
        "Grav": "Gravity furnace",
        "OthW": "Hot water/steam heat (non-gas)",
        "Wall": "Wall furnace",
    },
    "HeatingQC": {"Ex": "Excellent", "Gd": "Good", "TA": "Average/Typical", "Fa": "Fair", "Po": "Poor"},
    "CentralAir": {"N": "No", "Y": "Yes"},
    "Electrical": {
        "SBrkr": "Standard Circuit Breakers & Romex",
        "FuseA": "Fuse Box >60 AMP, all Romex (Average)",
        "FuseF": "60 AMP Fuse Box, mostly Romex (Fair)",
        "FuseP": "60 AMP Fuse Box, mostly knob & tube (Poor)",
        "Mix": "Mixed",
    },
    "KitchenQual": {"Ex": "Excellent", "Gd": "Good", "TA": "Typical/Average", "Fa": "Fair", "Po": "Poor"},
    "Functional": {
        "Typ": "Typical Functionality",
        "Min1": "Minor Deductions 1",
        "Min2": "Minor Deductions 2",
        "Mod": "Moderate Deductions",
        "Maj1": "Major Deductions 1",
        "Maj2": "Major Deductions 2",
        "Sev": "Severely Damaged",
        "Sal": "Salvage only",
    },
    "FireplaceQu": {
        "Ex": "Excellent - Exceptional Masonry Fireplace",
        "Gd": "Good - Masonry Fireplace (main level)",
        "TA": "Average - Prefab (main) or Masonry (basement)",
        "Fa": "Fair - Prefab (basement)",
        "Po": "Poor - Ben Franklin Stove",
        "NA": "No Fireplace",
    },
    "GarageType": {
        "2Types": "More than one type of garage",
        "Attchd": "Attached to home",
        "Basment": "Basement Garage",
        "BuiltIn": "Built-In (part of house; often room above)",
        "CarPort": "Car Port",
        "Detchd": "Detached from home",
        "NA": "No Garage",
    },
    "GarageFinish": {"Fin": "Finished", "RFn": "Rough Finished", "Unf": "Unfinished", "NA": "No Garage"},
    "GarageQual": {"Ex": "Excellent", "Gd": "Good", "TA": "Typical/Average", "Fa": "Fair", "Po": "Poor", "NA": "No Garage"},
    "GarageCond": {"Ex": "Excellent", "Gd": "Good", "TA": "Typical/Average", "Fa": "Fair", "Po": "Poor", "NA": "No Garage"},
    "PavedDrive": {"Y": "Paved", "P": "Partial Pavement", "N": "Dirt/Gravel"},
    "PoolQC": {"Ex": "Excellent", "Gd": "Good", "TA": "Average/Typical", "Fa": "Fair", "NA": "No Pool"},
    "Fence": {"GdPrv": "Good Privacy", "MnPrv": "Minimum Privacy", "GdWo": "Good Wood", "MnWw": "Minimum Wood/Wire", "NA": "No Fence"},
    "MiscFeature": {"Elev": "Elevator", "Gar2": "2nd Garage (not in garage section)", "Othr": "Other", "Shed": "Shed (over 100 SF)", "TenC": "Tennis Court", "NA": "None"},
    "SaleType": {"WD": "Warranty Deed - Conventional", "CWD": "Warranty Deed - Cash", "VWD": "Warranty Deed - VA Loan", "New": "Home just constructed and sold", "COD": "Court Officer Deed/Estate", "Con": "Contract 15% Down payment regular terms", "ConLw": "Contract Low Down payment and low interest", "ConLI": "Contract Low Interest", "ConLD": "Contract Low Down", "Oth": "Other"},
    "SaleCondition": {"Normal": "Normal Sale", "Abnorml": "Abnormal Sale (trade, foreclosure, short sale)", "AdjLand": "Adjoining Land Purchase", "Alloca": "Allocation (linked properties w/ separate deeds)", "Family": "Sale between family members", "Partial": "Home not completed when last assessed (New Homes)"},
}
